In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
pumpkins = pd.read_csv('data/US-pumpkins.csv')
pumpkins.head()

,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,Mostly Low,...,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,Unnamed: 24,Unnamed: 25
0,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,4/29/17,270.0,280.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,NaN,NaN
1,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,5/6/17,270.0,280.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,NaN,NaN
2,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,9/24/16,160.0,160.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
3,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,9/24/16,160.0,160.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
4,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/5/16,90.0,100.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# Drop rows with missing values
pumpkins.dropna(inplace=True)

# Check if there are any rows left after dropping missing values
if pumpkins.shape[0] == 0:
    print("No samples available after dropping missing values.")
    # You may want to handle this case, such as by loading the original dataset again or stopping the process.
else:
    # Convert date column to datetime
    pumpkins['Date'] = pd.to_datetime(pumpkins['Date'])

    # Standardize numeric columns
    numeric_cols = ['Low Price', 'High Price', 'Mostly Low', 'Mostly High']
    pumpkins[numeric_cols] = StandardScaler().fit_transform(pumpkins[numeric_cols])

    # One-hot encode categorical variables
    pumpkins = pd.get_dummies(pumpkins, columns=['City Name', 'Package', 'Variety', 'Sub Variety', 'Grade',
                                                 'Unit of Sale', 'Quality', 'Condition', 'Appearance',
                                                 'Storage', 'Crop', 'Repack', 'Trans Mode'])

    # Define features (X) and target variable (y)
    X = pumpkins.drop(['Date'], axis=1)
    y = pumpkins['Date'].apply(lambda x: 1 if x.month in [9, 10, 11] else 0)  # Binary classification: Autumn or not

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the Logistic Regression model
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # Visualize the results
    # Here, you can use different visualization techniques like confusion matrix, ROC curve, etc.
    # Let's plot the confusion matrix
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='g', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title('Confusion Matrix')
    plt.show()

    # Classification report
    print(classification_report(y_test, y_pred))

No samples available after dropping missing values.